<!DOCTYPE html>
<html lang="id">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Kelola Jurnal - Admin KSM</title>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />

  <!-- CSS Utama Admin -->
  <link rel="stylesheet" href="../../assets/css/admin/admin-main.css" />
  <link rel="shortcut icon" type="image/x-icon" href="../../assets/favicon.ico" />

  <script src="https://unpkg.com/feather-icons"></script>
</head>

<body>

  <!-- Header Admin -->
  <?php include 'components/header.html'; ?>

  <!-- Main Content -->
  <div class="container">

    <!-- Filter & Search Section -->
    <section class="filter-section">
      <div class="filter-row-top">
        <!-- Sort Dropdown -->
        <div class="sort-dropdown">
          <button class="btn-icon-sort" type="button" id="btnSort">
            <i data-feather="filter"></i>
          </button>
          <div class="sort-menu" id="sortMenu">
            <button data-sort="newest" class="sort-item active"><i data-feather="clock"></i> Terbaru</button>
            <button data-sort="oldest" class="sort-item"><i data-feather="calendar"></i> Terlama</button>
            <button data-sort="title" class="sort-item"><i data-feather="type"></i> Judul A-Z</button>
            <button data-sort="views" class="sort-item"><i data-feather="eye"></i> Paling Populer</button>
          </div>
        </div>

        <!-- Search Box -->
        <div class="search-box">
          <i data-feather="search"></i>
          <input type="text" placeholder="Cari jurnal..." id="searchInput" />
        </div>
      </div>

      <!-- Counter -->
      <div class="filter-row-bottom">
        <div class="filter-stats"><span id="totalJournals">0</span> jurnal</div>
      </div>
    </section>

    <!-- Back Button -->
    <section class="back-section">
      <a href="dashboard.php" class="btn-back">
        <i data-feather="arrow-left"></i> Back
      </a>
    </section>

    <!-- Journal List Section -->
    <section id="journal" class="journal-list-full">
      <div id="journalContainer">
        <!-- List generated by JS -->
      </div>
    </section>

    <!-- Pagination -->
    <section class="pagination-section">
      <div id="pagination" class="pagination"></div>
    </section>
  </div>

  <!--  EDIT MODAL (HANYA ADA DI ADMIN)  -->
  <div id="editModal" class="modal" style="display: none;">
    <div class="modal-overlay"></div>
    <div class="modal-content">
      <button id="closeEditModal" type="button" class="modal-close">&times;</button>

      <h2>Edit Jurnal</h2>

      <form id="editForm">
        <input type="hidden" id="editJournalId" />

        <div class="form-group">
          <label for="editJudulJurnal">Judul Jurnal</label>
          <input type="text" id="editJudulJurnal" required />
        </div>

        <div class="form-group">
          <label for="editEmail">Email</label>
          <input type="email" id="editEmail" />
        </div>

        <div class="form-group">
          <label for="editKontak">Kontak</label>
          <input type="text" id="editKontak" />
        </div>

        <div class="form-group">
          <label for="editVolume">Volume</label>
          <input type="text" id="editVolume" />
        </div>

        <div class="form-group">
          <label for="editAbstrak">Abstrak</label>
          <textarea id="editAbstrak" rows="5"></textarea>
        </div>

        <!-- Authors -->
        <div class="form-group">
          <label>Penulis</label>
          <div id="editAuthorsContainer">
            <!-- Dynamic inputs via JS -->
          </div>
          <button type="button" id="editAddAuthorBtn" class="btn-small">+ Tambah Penulis</button>
        </div>

        <!-- Pengurus -->
        <div class="form-group">
          <label>Pengurus</label>
          <div id="editPengurusContainer"></div>
          <button type="button" id="editAddPengurusBtn" class="btn-small">+ Tambah Pengurus</button>
        </div>

        <!-- Tags -->
        <div class="form-group">
          <label>Tags</label>
          <div id="editTagsContainer" class="tags-container"></div>
          <div class="tag-input-row">
            <input type="text" id="editTagInput" placeholder="Tambahkan tag" />
            <button type="button" id="editAddTagBtn" class="btn-small">+ Tambah</button>
          </div>
        </div>

        <!-- File Inputs -->
        <div class="form-group">
          <label for="editFileInput">File PDF (Biarkan kosong jika tidak diubah)</label>
          <input type="file" id="editFileInput" accept="application/pdf" />
        </div>

        <div class="form-group">
          <label for="editCoverInput">Cover (Biarkan kosong jika tidak diubah)</label>
          <input type="file" id="editCoverInput" accept="image/*" />
        </div>

        <div class="form-actions">
          <button type="button" id="cancelEdit" class="btn-secondary">Batal</button>
          <button type="submit" class="btn-primary">Simpan Perubahan</button>
        </div>
      </form>
    </div>
  </div>

  <!-- Scripts -->
  <script src="../../js/api.js"></script>
  <script src="../../js/storage.js"></script>

  <!-- Script Khusus Admin (Logic Edit/Delete/Upload) -->
  <script src="../../js/file_upload.js"></script>
  <script src="../../js/jurnal_admin.js"></script>

  <script>
    feather.replace();
  </script>
</body>

</html>