<!DOCTYPE html>
<html lang="id">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Kelola Opini - Admin KSM</title>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />

  <!-- CSS Utama Admin -->
  <link rel="stylesheet" href="../../assets/css/admin-main.css" />
  <link rel="shortcut icon" type="image/x-icon" href="../../assets/favicon.ico" />

  <script src="https://unpkg.com/feather-icons"></script>
</head>

<body>

  <?php
  require_once '../../config/config.php';
  ?>

  <!-- Header Admin -->
  <?php include 'components/header.html'; ?>

  <!-- Main Content -->
  <div class="container">

    <!-- Filter & Search Section -->
    <section class="filter-section">
      <div class="filter-row-top">
        <!-- Sort Dropdown -->
        <div class="sort-dropdown">
          <button class="btn-icon-sort" type="button" id="btnSort">
            <i data-feather="filter"></i>
          </button>
          <div class="sort-menu" id="sortMenu">
            <button data-sort="newest" class="sort-item active">
              <i data-feather="clock"></i> Terbaru
            </button>
            <button data-sort="oldest" class="sort-item">
              <i data-feather="calendar"></i> Terlama
            </button>
            <button data-sort="title" class="sort-item">
              <i data-feather="type"></i> Judul A-Z
            </button>
            <button data-sort="views" class="sort-item">
              <i data-feather="eye"></i> Paling Populer
            </button>
          </div>
        </div>

        <!-- Search Box -->
        <div class="search-box">
          <i data-feather="search"></i>
          <input type="text" placeholder="Cari opini..." id="searchInput" />
        </div>
      </div>

      <!-- Counter -->
      <div class="filter-row-bottom">
        <div class="filter-stats">
          <span id="totalJournals">0</span> opini
        </div>
      </div>
    </section>

    <!-- Back Button -->
    <section class="back-section">
      <a href="dashboard.php" class="btn-back">
        <i data-feather="arrow-left"></i> Back
      </a>
    </section>

    <!-- Opinion List Section -->
    <section id="journal" class="journal-list-full">
      <div id="journalContainer">
        <!-- List generated by JS -->
      </div>
    </section>

    <!-- Pagination -->
    <section class="pagination-section">
      <div id="pagination" class="pagination"></div>
    </section>
  </div>

  <!--  SHARE MODAL  -->
  <div id="shareModal" class="modal" style="display: none;">
    <div class="modal-overlay"></div>
    <div class="modal-content" style="max-width: 500px;">
      <button onclick="closeShareModal()" class="modal-close" type="button">&times;</button>

      <h2 style="margin-bottom: 20px;">Bagikan Artikel</h2>

      <div class="share-url-box" style="display: flex; gap: 10px; margin-bottom: 20px;">
        <input
          type="text"
          id="shareUrlInput"
          readonly
          style="flex: 1; padding: 12px; border: 1px solid #ddd; border-radius: 8px; font-size: 14px;" />
        <button
          onclick="copyShareLink()"
          class="btn-primary"
          type="button"
          style="padding: 12px 20px; white-space: nowrap;">
          <i data-feather="copy"></i> Salin
        </button>
      </div>

      <div class="share-social" style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px;">
        <button
          onclick="shareToWhatsApp()"
          class="btn-social whatsapp"
          type="button"
          style="padding: 12px; background: #25d366; color: white; border: none; border-radius: 8px; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 8px; font-weight: 600;">
          <i data-feather="message-circle"></i> WhatsApp
        </button>
        <button
          onclick="shareToFacebook()"
          class="btn-social facebook"
          type="button"
          style="padding: 12px; background: #1877f2; color: white; border: none; border-radius: 8px; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 8px; font-weight: 600;">
          <i data-feather="facebook"></i> Facebook
        </button>
        <button
          onclick="shareToTwitter()"
          class="btn-social twitter"
          type="button"
          style="padding: 12px; background: #1da1f2; color: white; border: none; border-radius: 8px; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 8px; font-weight: 600;">
          <i data-feather="twitter"></i> Twitter
        </button>
      </div>
    </div>
  </div>

  <!--  EDIT MODAL (KHUSUS ADMIN)  -->
  <div id="editModal" class="modal" style="display: none;">
    <div class="modal-overlay"></div>
    <div class="modal-content">
      <button id="closeEditModal" type="button" class="modal-close">&times;</button>

      <h2>Edit Opini</h2>

      <form id="editForm">
        <input type="hidden" id="editJournalId" />

        <div class="form-group">
          <label for="editJudulJurnal">Judul Opini</label>
          <input type="text" id="editJudulJurnal" required />
        </div>

        <div class="form-group">
          <label for="editEmail">Email</label>
          <input type="email" id="editEmail" />
        </div>

        <div class="form-group">
          <label for="editKontak">Kontak</label>
          <input type="text" id="editKontak" />
        </div>

        <div class="form-group">
          <label for="editAbstrak">Deskripsi</label>
          <textarea id="editAbstrak" rows="5"></textarea>
        </div>

        <!-- Authors -->
        <div class="form-group">
          <label>Penulis</label>
          <div id="editAuthorsContainer">
          </div>
          <button type="button" id="editAddAuthorBtn" class="btn-small">+ Tambah Penulis</button>
        </div>

        <!-- Pengurus -->
        <div class="form-group">
          <label>Pengurus</label>
          <div id="editPengurusContainer"></div>
          <button type="button" id="editAddPengurusBtn" class="btn-small">+ Tambah Pengurus</button>
        </div>

        <!-- Tags -->
        <div class="form-group">
          <label>Tags</label>
          <div id="editTagsContainer" class="tags-container"></div>
          <div class="tag-input-row">
            <input type="text" id="editTagInput" placeholder="Tambahkan tag" />
            <button type="button" id="editAddTagBtn" class="btn-small">+ Tambah</button>
          </div>
        </div>

        <!-- File Inputs -->
        <div class="form-group">
          <label for="editFileInput">File PDF (Biarkan kosong jika tidak diubah)</label>
          <input type="file" id="editFileInput" accept="application/pdf" />
        </div>

        <div class="form-group">
          <label for="editCoverInput">Cover (Biarkan kosong jika tidak diubah)</label>
          <input type="file" id="editCoverInput" accept="image/*" />
        </div>

        <div class="form-actions">
          <button type="button" id="cancelEdit" class="btn-secondary">Batal</button>
          <button type="submit" class="btn-primary">Simpan Perubahan</button>
        </div>
      </form>
    </div>
  </div>

  <!-- Scripts -->
  <script src="../../js/api.js"></script>
  <script src="../../js/storage.js"></script>

  <!-- Script Khusus Opini Admin -->
  <script src="../../js/file_upload.js"></script>
  <script src="../../js/opinions_admin.js"></script>
  <script src="../../js/edit_opinion.js"></script>
  <script src="../../js/social.js"></script>

  <script>
    feather.replace();
  </script>
</body>

</html>