<?php
$page_title = 'KSM Education';
$base_css = '<link rel="stylesheet" href="../styles/dashboard_user.css?v=20260718" />
  <link rel="stylesheet" href="../styles/token_wallet.css?v=20260715" />
  <link rel="stylesheet" href="../styles/upload_journal_modal.css?v=20260715" />
  <link rel="stylesheet" href="../styles/ad_carousel.css?v=20260717" />';
include 'components/header.php';
include 'components/navbar.php';
?>


    <!-- Main Content -->
    <div class="container">

      <?php
      // ===== CAROUSEL IKLAN / PROMOSI (auto-geser tiap beberapa detik) =====
      include 'components/ad_carousel.php';
      ?>

      <!-- Statistics Section -->
      <section class="statistics">
        <h2>Statistik</h2>
        <div class="stats-grid">
          <div class="stat-card">
            <div class="stat-icon">
              <i data-feather="bar-chart-2"></i>
            </div>
            <div class="stat-number skeleton-stat" id="articleCount"></div>
            <div class="stat-label">ARTIKEL</div>
          </div>
          <div class="stat-card">
            <div class="stat-icon">
              <i data-feather="eye"></i>
            </div>
            <div class="stat-number skeleton-stat" id="visitorCount"></div>
            <div class="stat-label">Pengunjung</div>
          </div>

          <!-- ===== KARTU TOKEN SAYA ===== -->
          <div class="ksm-token-card">
            <div class="stat-icon">
              <i data-feather="zap" ></i>
            </div>
            <div class="stat-number" data-ksm-token-balance>0</div>
            <div class="stat-label">Token Saya</div>
          </div>
        </div>
      </section>

      <!-- ===== ARTIKEL SAYA + AKTIVITAS TERBARU (two-column) ===== -->
      <section class="dashboard-two-col">

        <!-- LEFT: Artikel Terbaru Saya -->
        <div class="my-articles-card">
          <div class="dtc-card-header">
            <h3>Artikel Terbaru Saya</h3>
            <a href="my_journals_user.php" class="dtc-see-all">
              Lihat Semua
              <i data-feather="arrow-right"></i>
            </a>
          </div>
          <div class="my-articles-list" id="myArticlesList">
            <!-- Rendered by JS: renderMyArticles() -->
          </div>
        </div>

        <!-- RIGHT: Aktivitas Terbaru -->
        <div class="activity-card">
          <div class="dtc-card-header">
            <h3>Aktivitas Terbaru</h3>
            <a href="token_history_user.php" class="dtc-see-all dtc-see-all-dark">
              Lihat Semua
              <i data-feather="arrow-right"></i>
            </a>
          </div>
          <div class="activity-list" id="activityList">
            <!-- Rendered by JS: renderActivityFeed() -->
          </div>
        </div>

      </section>

      <!-- ===== BANNER CTA: PUNYA KARYA UNTUK DIBAGIKAN ===== -->
      <section class="ksm-token-cta">
        <div class="ksm-token-cta-text">
          <h3>Punya Karya untuk Dibagikan?</h3>
          <p>
            Upload jurnal atau opini Anda menggunakan token. Setiap upload
            membutuhkan 1 token — belum punya token? Beli dulu, lalu upload
            karya Anda ke KSM Education.
          </p>
        </div>
        <div class="ksm-token-cta-actions">
          <button type="button" class="ksm-btn-outline-light" data-ksm-open-buy-token>
            <i data-feather="shopping-cart"></i>
            Beli Token
          </button>
          <button type="button" class="ksm-btn-solid-light" data-ksm-open-upload>
            <i data-feather="upload"></i>
            Upload Jurnal Baru
          </button>
        </div>
      </section>

      <!-- Articles Section -->
      <section class="articles-section">
        <h2>Artikel Terbaru</h2>
        <div class="articles-wrapper">
          <div class="articles-grid" id="articlesGrid">
            <!-- Articles will be generated by JavaScript -->
          </div>
        </div>
        <div id="latestArticlesNavUser"></div>
      </section>

      <!-- Categories Section -->
      <section class="categories-section">
        <h2>Kategori Populer</h2>
        <div class="categories-grid">
          <div class="category-card">
            <span class="category-name">Social</span>
            <span class="category-count">(17)</span>
          </div>
          <div class="category-card">
            <span class="category-name">International</span>
            <span class="category-count">(84)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Crime</span>
            <span class="category-count">(32)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Accident</span>
            <span class="category-count">(24)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Political</span>
            <span class="category-count">(155)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Sports</span>
            <span class="category-count">(1952)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Health</span>
            <span class="category-count">(143)</span>
          </div>
          <div class="category-card">
            <span class="category-name">Education</span>
            <span class="category-count">(91)</span>
          </div>
        </div>
      </section>

    </div>

    <?php
    // ===== MODALS: Token & Upload (shared partials) =====
    include 'components/token_modal.php';
    include 'components/upload_journal_modal.php';
    ?>

    <!-- Main Footer -->


    <!-- Scripts -->

<?php
$extra_scripts = <<<'EOT'
    <script src="../js/script.js?v=20260722"></script>
    <script src="../js/custom_alerts.js"></script>
    <script src="../js/statistic.js?v=20251130"></script>
    <script src="../js/jurnal.js?v=20260321"></script>
    <script src="../js/opinions_manager.js"></script>
    <script src="../js/file_upload.js"></script>
    <script src="../js/dashboard_user.js?v=20260718"></script>
    <script src="../js/token_wallet.js?v=20260715"></script>
    <script src="../js/upload_journal_modal.js?v=20260715"></script>
    <script src="../js/ad_carousel.js?v=20260717"></script>
    <script src="../js/mobile_menu.js?v=20251130"></script>
    <script>
      feather.replace();
    </script>
  
EOT;
include 'components/footer.php';
?>